# This workflow will build and push a node.js application to an Azure Web App when a release is created.
on:
  push:
    branches:
      - main
env:
  NODE_VERSION: '14.x'                # set this to the node version to use
  OBJECT_LOCATION: public
  DESTINATION_BUCKET_NAME:  cms-kernwestfale-de

jobs:
  build-and-deploy:
    name: Build and Deploy to Google
    runs-on: ubuntu-latest
    environment: production
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.NODE_VERSION }}
    #- run:
    #      name: Install Hexo CLI
    #      command: npm install -g hexo-cli
    #- name: npm install, build
    #  run: |
    #    hexo generate
    #- name: Set up Cloud SDK
    #  uses: google-github-actions/setup-gcloud@master
    #  with:
    #    project_id: ${{ secrets.GCP_PROJECT_ID }}
    #    service_account_key: ${{ secrets.GCP_SA_KEY }}
    #    export_default_credentials: true
    #- name: Upload to google
    #  run: |
    #      gsutil cp OBJECT_LOCATION gs://DESTINATION_BUCKET_NAME/
          
